#name: CI/CD
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  run-fastapi:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#          pip install uvicorn fastapi
#
#      - name: Start FastAPI app (just test if it starts)
#        run: |
#          uvicorn api.main:app --host 0.0.0.0 --port 8000 --lifespan on --timeout-keep-alive 1 &
#          sleep 5
#          curl -f http://127.0.0.1:8000/docs || exit 1



name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run FastAPI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc

      - name: Pull model with DVC
        run: |
          dvc pull
        env:
          DVC_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

      - name: Run FastAPI
        run: |
          uvicorn api.main:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: Test FastAPI endpoint
        run: |
          curl -X GET http://127.0.0.1:8000/docs || exit 1

  deploy:
    name: Deploy FastAPI (optional)
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc

      - name: Pull model with DVC
        run: |
          dvc pull
        env:
          DVC_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

      - name: Deploy placeholder
        run: |
          echo "Deploy FastAPI to Render/Heroku/etc"

