name: CI/CD Pipeline with DVC & DAGsHub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Run tests
        run: |
          pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python & DVC
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Configure DVC Remote
        run: |
          dvc remote add origin https://dagshub.com/${{ secrets.pechnary15 }}/${{ secrets.DAGSHUB_REPO }}.dvc
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USER }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Commit and Push Model to DAGsHub
        run: |
          dvc add models/best_model.joblib
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add models/best_model.joblib.dvc dvc.lock
          git commit -m "Track model via CI/CD" || echo "No changes to commit"
          git push origin main
          dvc push