name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gs,s3,azure,ssh,webdav,oss]  # installs DAGsHub-compatible remotes

      - name: Pull model with DVC
        run: |
          dvc pull
        env:
          DVC_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

      - name: Run FastAPI
        run: |
          uvicorn api.main:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: Test FastAPI endpoint
        run: |
          curl -X GET http://127.0.0.1:8000/docs || exit 1

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gs,s3,azure,ssh,webdav,oss]

      - name: Pull model with DVC
        run: |
          dvc pull
        env:
          DVC_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

      - name: Deploy Step (Placeholder)
        run: |
          echo "Deploy FastAPI to Render/Heroku/VPS here"

