name: Deploy API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        ssh user@server <<EOF
          cd /app/wine-classification
          git pull
          docker-compose down
          docker-compose up -d --build
        EOF
